---
name: "Publish README job"
on:
  push:
    branches:
      - main
  schedule:
    - cron: '15 0 * * *'

jobs:
  update-readme:
    name: "Python job"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          pip install -r requirements.txt

      - name: Run script to update README
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        run: python -m src.main

      - name: Upload file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: job-result
          path: README.md
